baseURL = "https://lbbikecoop.org"
title = "Long Beach Bike Co-Op"
theme = "hugo-universal-theme"
languageCode = "en-us"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[markup]
  [markup.goldmark.renderer]
    unsafe=true

# Define the number of posts per page
[pagination]
    pagerSize = 10

# Main menu
[menu]
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/about"
    weight     = 2

[[menu.main]]
    name       = "Workshop"
    identifier = "menu.workshop"
    url        = "/workshop"
    weight     = 3

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact"
    weight     = 4

[[menu.main]]
    name       = "Donate"
    identifier = "menu.donate"
    url        = "/donate"
    weight     = 5

# Top bar social links menu
[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:(562) 204-6747"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:hello@lbbikecoop.org"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 3
    name = "Instagram"
    url = "https://www.instagram.com/long_beach_bike_co_op/"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Devin"
    defaultKeywords = ["bicycle", "coop", "bike", "shop"]
    mainSections = ["blog"]
    defaultDescription = "Long Beach Bicycle Co-Op"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    copyright = "Copyright © 2025, Long Beach Bike Co-Op"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Long Beach Bike Co-Op"
    logo = "img/LBBC_corner_logo.png"
    logo_small = "img/LBBC_corner_logo.png"

    contact_url = "/contact"

[permalinks]
    blog = "/blog/:year/:month/:day/:contentbasename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = false
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to learn more?"
    subtitle = "Join out mailing list to stay up to date."
    link_url = "#"
    link_text = "Join"

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
